export const PROVINCIAS = [
  { value: 'BUENOS_AIRES', label: 'Buenos Aires' },
  { value: 'CABA', label: 'Ciudad Autónoma de Buenos Aires' },
  { value: 'CATAMARCA', label: 'Catamarca' },
  { value: 'CHACO', label: 'Chaco' },
  { value: 'CHUBUT', label: 'Chubut' },
  { value: 'CORDOBA', label: 'Córdoba' },
  { value: 'CORRIENTES', label: 'Corrientes' },
  { value: 'ENTRE_RIOS', label: 'Entre Ríos' },
  { value: 'FORMOSA', label: 'Formosa' },
  { value: 'JUJUY', label: 'Jujuy' },
  { value: 'LA_PAMPA', label: 'La Pampa' },
  { value: 'LA_RIOJA', label: 'La Rioja' },
  { value: 'MENDOZA', label: 'Mendoza' },
  { value: 'MISIONES', label: 'Misiones' },
  { value: 'NEUQUEN', label: 'Neuquén' },
  { value: 'RIO_NEGRO', label: 'Río Negro' },
  { value: 'SALTA', label: 'Salta' },
  { value: 'SAN_JUAN', label: 'San Juan' },
  { value: 'SAN_LUIS', label: 'San Luis' },
  { value: 'SANTA_CRUZ', label: 'Santa Cruz' },
  { value: 'SANTA_FE', label: 'Santa Fe' },
  { value: 'SANTIAGO_DEL_ESTERO', label: 'Santiago del Estero' },
  { value: 'TIERRA_DEL_FUEGO', label: 'Tierra del Fuego' },
  { value: 'TUCUMAN', label: 'Tucumán' },
];

export const GRADUACIONES = [
  { value: 'SIN_GRADUACION', label: 'Sin graduación' },
  { value: '3_KYU', label: '3° Kyu' },
  { value: '2_KYU', label: '2° Kyu' },
  { value: '1_KYU', label: '1° Kyu' },
  { value: '1_DAN', label: '1° Dan' },
  { value: '2_DAN', label: '2° Dan' },
  { value: '3_DAN', label: '3° Dan' },
  { value: '4_DAN', label: '4° Dan' },
  { value: '5_DAN', label: '5° Dan' },
  { value: '6_DAN', label: '6° Dan' },
  { value: '7_DAN', label: '7° Dan' },
  { value: '8_DAN', label: '8° Dan' },
];
